version: "3.8"

services:

  memory-db:
    extends:
      file: docker-compose-template-services.yaml
      service: template-db
    container_name: ${DEPLOYMENT_NAME}-memory-db
    volumes:
    - memory-db:/var/lib/postgresql/data

  memory-backend:
    extends:
      file: docker-compose-template-services.yaml
      service: template-backend
    container_name: ${DEPLOYMENT_NAME}-memory-backend
    image: ghcr.io/gamify-it/memory-backend:$VERSION
    depends_on:
      - memory-db
    environment:
      - POSTGRES_URL=postgresql://${DEPLOYMENT_NAME}-memory-db:5432/postgres

  memory:
    extends:
      file: docker-compose-template-services.yaml
      service: template-frontend
    container_name: ${DEPLOYMENT_NAME}-memory
    image: ghcr.io/gamify-it/memory:$VERSION

volumes:
  memory-db:
    name: ${DEPLOYMENT_NAME}-memory-db
