version: "3.8"

services:

  towercrush-db:
    extends:
      file: docker-compose-template-services.yaml
      service: template-db
    container_name: ${DEPLOYMENT_NAME}-towercrush-db
    volumes:
    - towercrush-db:/var/lib/postgresql/data

  towercrush-backend:
    extends:
      file: docker-compose-template-services.yaml
      service: template-backend
    container_name: ${DEPLOYMENT_NAME}-towercrush-backend
    image: ghcr.io/gamify-it/towercrush-backend:$VERSION
    depends_on:
      - bugfinder-db
    environment:
      - POSTGRES_URL=postgresql://${DEPLOYMENT_NAME}-towercrush-db:5432/postgres

  towercrush:
    extends:
      file: docker-compose-template-services.yaml
      service: template-frontend
    container_name: ${DEPLOYMENT_NAME}-towercrush
    image: ghcr.io/gamify-it/towercrush:$VERSION

volumes:
  towercrush-db:
    name: ${DEPLOYMENT_NAME}-towercrush-db
