version: "3.8"

services:

  keycloak-db:
    extends:
      file: docker-compose-template-services.yaml
      service: template-db
    container_name: ${DEPLOYMENT_NAME}-keycloak-db
    volumes:
      - keycloak-db:/var/lib/postgresql/data

  keycloak:
    extends:
      file: docker-compose-template-services.yaml
      service: template-service
    container_name: ${DEPLOYMENT_NAME}-keycloak
    image: ghcr.io/gamify-it/keycloak:$VERSION
    depends_on:
      - keycloak-db
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB_URL=jdbc:postgresql://${DEPLOYMENT_NAME}-keycloak-db:5432/postgres
      - KC_HOSTNAME_URL=${EXTERNAL_URL}/keycloak
    expose:
      - "80"

volumes:
  keycloak-db:
    name: ${DEPLOYMENT_NAME}-keycloak-db
