apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ###DEPLOYMENT_NAME###-reverse-proxy
  name: ###DEPLOYMENT_NAME###-reverse-proxy
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: ###DEPLOYMENT_NAME###-reverse-proxy
status:
  loadBalancer: {}
